[package]
name = "saule-typeck"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
saule-ast = { path = "../saule-ast" }
saule-semantic = { path = "../saule-semantic" }
miette = "7.6.0"
thiserror = "2.0.18"

[dev-dependencies]
saule-lexer = { path = "../saule-lexer" }
saule-parser = { path = "../saule-parser" }
