[package]
name = "saule-cli"
version.workspace = true
edition.workspace = true
description.workspace = true

[[bin]]
name = "saule"
path = "src/main.rs"

[dependencies]
saule-lexer = { path = "../saule-lexer" }
saule-parser = { path = "../saule-parser" }
saule-interpreter = { path = "../saule-interpreter" }
miette = { version = "7.6.0", features = ["fancy"] }
